# Generated by Django 3.2.5 on 2021-07-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='numbers',
            field=models.IntegerField(),
        ),
    ]
