# Generated by Django 3.2.5 on 2021-07-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0002_alter_plate_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='letters',
            field=models.CharField(default='YUO', max_length=3),
        ),
        migrations.AlterField(
            model_name='plate',
            name='numbers',
            field=models.CharField(default='932', max_length=3),
        ),
    ]
