# Generated by Django 3.2.5 on 2021-07-11 15:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0003_auto_20210711_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plate',
            name='letters',
            field=models.CharField(default='LWI', max_length=3),
        ),
        migrations.AlterField(
            model_name='plate',
            name='numbers',
            field=models.CharField(default='393', max_length=3),
        ),
    ]
