# Generated by Django 3.2.5 on 2021-07-11 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0005_auto_20210711_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plate',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='plate',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plate',
            name='letters',
            field=models.CharField(default='BKS', max_length=3),
        ),
        migrations.AlterField(
            model_name='plate',
            name='numbers',
            field=models.CharField(default='969', max_length=3),
        ),
    ]
