# Generated by Django 3.2.5 on 2021-07-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0006_auto_20210711_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='letters',
            field=models.CharField(default='YOX', max_length=3),
        ),
        migrations.AlterField(
            model_name='plate',
            name='numbers',
            field=models.CharField(default='669', max_length=3),
        ),
    ]
