# Generated by Django 3.2.5 on 2021-07-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0013_auto_20210711_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='letters',
            field=models.CharField(default='PGI', max_length=3),
        ),
        migrations.AlterField(
            model_name='plate',
            name='numbers',
            field=models.CharField(default='624', max_length=3),
        ),
    ]
