# Generated by Django 3.2.5 on 2021-07-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0017_auto_20210712_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='letters',
            field=models.CharField(default='NDB', max_length=3),
        ),
        migrations.AlterField(
            model_name='plate',
            name='numbers',
            field=models.CharField(default='293', max_length=3),
        ),
    ]
