# Generated by Django 3.2.5 on 2021-07-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0021_auto_20210712_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='letters',
            field=models.CharField(blank=True, default='NSU', max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='plate',
            name='numbers',
            field=models.CharField(default='751', max_length=3),
        ),
    ]
