# Generated by Django 3.2.5 on 2021-07-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0022_auto_20210712_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='letters',
            field=models.CharField(blank=True, default='CC6', editable=False, max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='plate',
            name='numbers',
            field=models.CharField(default='261', max_length=3),
        ),
    ]
