# Generated by Django 3.2.5 on 2021-07-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0024_auto_20210712_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='letters',
            field=models.CharField(default='OS8', max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='plate',
            name='numbers',
            field=models.CharField(default='334', max_length=3),
        ),
    ]
