# Generated by Django 3.2.5 on 2021-07-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0026_auto_20210712_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='letters',
            field=models.CharField(default='YQY', max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='plate',
            name='numbers',
            field=models.CharField(default='873', max_length=3, unique=True),
        ),
    ]
