# Generated by Django 3.2.5 on 2021-07-12 11:57

from django.db import migrations, models
import plates.models


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0028_auto_20210712_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='letters',
            field=models.CharField(default=plates.models.random_letters, max_length=3),
        ),
        migrations.AlterField(
            model_name='plate',
            name='numbers',
            field=models.CharField(default=plates.models.random_numbers, max_length=3),
        ),
    ]
